### ISSUE TITLE
Use "index.html" as the filename of the spec.

### ISSUE THREAD

**Issue by AFBarstow** [w3c/clipboard-apis#1]
A common practice when gh-pages (branch) is used is name the main file "index.html". Unless there's a good reason to keep with "clipops.html", use "index.html" instead.

**Comment by darobin** [comment]
With that in mind, I've made `gh-pages` your default branch. LMK if it's not what you wanted. I would also recommend deleting `master`.

**Comment by AFBarstow** [comment]
Deleting the master and origin branches make sense to me. OK with you @hallvors?

With the file rename, it's unfortunate Github no longer shows the past CVS history of the clipops-source.html. If the history can't be resurrected, perhaps the README should include a link to the CVS repo.

**Comment by hallvors** [comment]
Go ahead and delete the branches. What's the best link to the CVS history?

**Comment by AFBarstow** [comment]
@darobin @siusin would one of you please delete the master and origin branches for clipboard-apis? (I don't have permission to do so).

@hallvors I would use http://dev.w3.org/cvsweb/2006/webapi/clipops/ (and can add it to the README if you'd like).

**Comment by ylafon** [comment]
@AFBarstow done.

**Comment by AFBarstow** [comment]
@hallvors, re the CVS history, actually it does exist via <https://github.com/w3c/clipboard-apis/commits/gh-pages> but not via index.html's commit history <https://github.com/w3c/clipboard-apis/commits/gh-pages/index.html>. Nevertheless, it still would probably be useful for README to include a link to CVS directory.

@ylafon, thanks!

**Comment by hallvors** [comment]
Sure, just add it :)
