### ISSUE TITLE
Is "clipboard" permission replaced by "clipboard-read" and "clipboard-write"?

### ISSUE THREAD

**Issue by saschanaz** [w3c/clipboard-apis#101]
[The Permissions spec](https://w3c.github.io/permissions/#dom-permissionname-clipboard) still mentions `"clipboard"` but it seems it's removed from the Clipboard spec. Should the Permissons spec be updated to use the new permission names?

**Comment by saschanaz** [comment]
@marcoscaceres Kinda, but that seems outdated. It still uses `"clipboard"` instead of `"clipboard-read"` and `"clipboard-write"`, which doesn't match this spec.

**Comment by nickalbrecht** [comment]
Any traction on this one?

**Comment by saschanaz** [comment]
Can somebody confirm this please so that I can open a PR there?

**Comment by marcoscaceres** [comment]
A PR would be good. I know what the implementation status of any of this is, however. @saschanaz, would you mind investigating a little bit?

**Comment by saschanaz** [comment]
Firefox Nightly: No support
Chrome (as of 80 stable): Support for `clipboard-read` and `clipboard-write`
Epiphany (WebKit): No `navigator.permissions` support at all

**Comment by marcoscaceres** [comment]
Much sadness... let me see if I can find who own clipboard on the Gecko side.

**Comment by saschanaz** [comment]
Related Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1560373

**Comment by marcoscaceres** [comment]
Good find! thank you!

**Comment by saschanaz** [comment]
Does that mean there is no owner? Should I wait until someone takes it?

**Comment by annevk** [comment]
Yeah, it's not clear to me how much buy-in the current setup has here so I'd definitely hold off a bit for now.

**Comment by rniwa** [comment]
FWIW, Safari will likely never support non-gesture based copy & paste permission (as in we'd likely always require a new gesture for each copy & paste). As such, we don't see this permission ever being implemented / supported in Safari.

**Comment by wandyezj** [comment]
What is really annoying is that browsers have gone ahead with their own implementation for a critical feature. This ends up forcing developers to use commands to read and write to the clipboard to work around this nonsense.

This seems like a people problem and not a technical problem.
