### ISSUE TITLE
Should the constructor of ClipboardItem accept record<DOMString, ClipboardItemDataType>?

### ISSUE THREAD

**Issue by whsieh** [w3c/clipboard-apis#102]
Currently, the first argument in ClipboardItem’s constructor takes a record of `DOMString` to `ClipboardItemData`, which is a `Promise<ClipboardItemDataType>` where `ClipboardItemDataType` is either a string or a blob.

However, the following code:

```
const item = new ClipboardItem({
    "text/plain" : new Blob(["foo"], { type: "text/plain" })
});
```

works fine in Chrome 77.0.3865.120, whereas:

```
const item = new ClipboardItem({
    "text/plain" : new Promise(r => r(new Blob(["foo"], { type: "text/plain" })))
});
```

results in `TypeError: Failed to construct 'ClipboardItem': Failed to convert value to 'Blob’.`. Should the spec be revised to allow for either `ClipboardItemData` or `ClipboardItemDataType` as record values?

For reference: https://www.w3.org/TR/clipboard-apis/#clipboarditem

**Comment by mkruisselbrink** [comment]
First of all, WebIDL does not support a method accepting either a promise type or a non-promise type (i.e. "Promise types [...] are not distinguishable with any other type."). But in this case that doesn't matter either. The way WebIDL converts an ecmascript value to a Promise type implicitly wraps any non-promise type in a promise anyway, so by accepting ClipboardItemData, the method already accepts ClipboardItemDataType as well.
