### ISSUE TITLE
mac os doesn't recognize 'image/svg+xml' mime type

### ISSUE THREAD

**Issue by alexsong19** [w3c/clipboard-apis#105]
On windows, I can copy svg content to clipboard, with mime type 'image/svg+xml', and then paste to other programs as a vector graph.
On mac os, this doesn't seem to work. In mac os clipboard, the file type would become 'unkonwn'.
An example python code is as follows, I use `matplotlib` to generate a svg graph, then use `PyQt` to send it to clipboard:
```
import io
import numpy as np
from PySide.QtGui import QApplication, QImage
from matplotlib import pyplot as plt
import matplotlib as mpl

mpl.use('Qt5Agg') # or Qt4Agg

# do a matplotlib plot
fig = plt.figure()
plt.plot(np.arange(10), np.arange(10))

# this saves the plot as svg to clipboard
buf = io.BytesIO()
fig.savefig(buf, format='svg')
data = QtCore.QMimeData()
data.setData('image/svg+xml', buf.getvalue())
QApplication.clipboard().setMimeData(data)
```
This works on windows but not on mac. 

Is this because mac osx clipboard doesn't recognize 'imag/svg+xml'?

**Comment by rniwa** [comment]
I don't see how this relates to Clipboard API on the Web?

**Comment by alexsong19** [comment]
> I don't see how this relates to Clipboard API on the Web?

sorry posted in the wrong place; could you suggest the relevant repo to raise this?

**Comment by rniwa** [comment]
> > I don't see how this relates to Clipboard API on the Web?
>
> sorry posted in the wrong place; could you suggest the relevant repo to raise this?

Probably stackoverflow.

**Comment by alexsong19** [comment]
> > > I don't see how this relates to Clipboard API on the Web?
> > 
> > 
> > sorry posted in the wrong place; could you suggest the relevant repo to raise this?
> 
> Probably stackoverflow.

Tried, nobody answered me. Seems w3c and apple didn't sort this out, and I don't know who or where to ask...
https://stackoverflow.com/questions/58795424/how-does-macos-handle-image-svgxml-type-mime-data-in-clipboard

**Comment by rniwa** [comment]
> > > > I don't see how this relates to Clipboard API on the Web?
> > > 
> > > 
> > > sorry posted in the wrong place; could you suggest the relevant repo to raise this?
> > 
> > 
> > Probably stackoverflow.
> 
> Tried, nobody answered me. Seems w3c and apple didn't sort this out, and I don't know who or where to ask...
> https://stackoverflow.com/questions/58795424/how-does-macos-handle-image-svgxml-type-mime-data-in-clipboard

How to use operating system's clipboard implementation (in Cocoa platforms they're called pasteboards) is completely outside the realm of what W3C deals with. W3C is a standard organization for the Web, not every operating system in existence.

As a disclaimer, I'm an engineer at Apple's WebKit team but I sill won't be able to answer your question because the underlying Cocoa API does not use MIME type as means of tracking types of data in pasteboard. Instead, [NSPasteboard](https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc) is used. There is a set of [globally known types](https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc) but your program can also register a [new UTI](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_declare/understand_utis_declare.html#//apple_ref/doc/uid/TP40001319-CH204-SW4) and use that instead. Again, MIME type doesn't come into play.

**Comment by alexsong19** [comment]
> > > > > I don't see how this relates to Clipboard API on the Web?
> > > > 
> > > > 
> > > > sorry posted in the wrong place; could you suggest the relevant repo to raise this?
> > > 
> > > 
> > > Probably stackoverflow.
> > 
> > 
> > Tried, nobody answered me. Seems w3c and apple didn't sort this out, and I don't know who or where to ask...
> > https://stackoverflow.com/questions/58795424/how-does-macos-handle-image-svgxml-type-mime-data-in-clipboard
> 
> How to use operating system's clipboard implementation (in Cocoa platforms they're called pasteboards) is completely outside the realm of what W3C deals with. W3C is a standard organization for the Web, not every operating system in existence.
> 
> As a disclaimer, I'm an engineer at Apple's WebKit team but I sill won't be able to answer your question because the underlying Cocoa API does not use MIME type as means of tracking types of data in pasteboard. Instead, [NSPasteboard](https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc) is used. There is a set of [globally known types](https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc) but your program can also register a [new UTI](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_declare/understand_utis_declare.html#//apple_ref/doc/uid/TP40001319-CH204-SW4) and use that instead. Again, MIME type doesn't come into play.
> 
> If I were to guess this is an issue with Qt framework. It probably doesn't know what UTI to create for the SVG MIME type. But again, this topic is completely outside the scope of this repository.

I apologize again for asking in the wrong place. But it seems I stumbled into the right guy to ask:) There are many new terms for me. It sounds like although Qt takes arguments in the MIME type, but behind the scenes it converts to whatever the system understands. It just so happens that apple os (or NSPasteboard) don't have a standard type for svg, as I can't find it in the [list](https://developer.apple.com/documentation/appkit/nspasteboardtype?language=objc) you mentioned. But windows clipboard does use MIME so there's no problem?

**Comment by rniwa** [comment]
> I apologize again for asking in the wrong place. But it seems I stumbled into the right guy to ask:) There are many new terms for me. It sounds like although Qt takes arguments in the MIME type, but behind the scenes it converts to whatever the system understands. It just so happens that apple os (or NSPasteboard) don't have a standard type for svg, as I can't find it in the list you mentioned. But windows clipboard does use MIME so there's no problem?

It looks like we do have UTI for SVG: https://developer.apple.com/documentation/coreservices/kuttypescalablevectorgraphics?language=objc so this is probably just a Qt bug that it doesn't know how to convert that SVG MIME type to this UTI. I suggest you work with folks maintaining Qt to resolve this issue.

**Comment by alexsong19** [comment]
> It looks like we do have UTI for SVG: https://developer.apple.com/documentation/coreservices/kuttypescalablevectorgraphics?language=objc so this is probably just a Qt bug that it doesn't know how to convert that SVG MIME type to this UTI. I suggest you work with folks maintaining Qt to resolve this issue.

Thank you so much again. This is very helpful!

**Comment by yisibl** [comment]
Macs should probably use `public.svg-image`

See: https://docs.google.com/document/d/1Rx7gi01avpRRNYKSpp3U4WQdjery0H0IkX2XxDtfZ8I/edit
