### ISSUE TITLE
Rephrase "direct user action" to match the new user activation model

### ISSUE THREAD

**Issue by mustaqahmed** [w3c/clipboard-apis#107]
We have User Activation v2 model in the HTML spec now. The current wording "running as a result of direct user action" should be changed accordingly. See the HTML issue mentioned below.

**Comment by marcoscaceres** [comment]
@saschanaz, would you be interested in taking this one on?

**Comment by saschanaz** [comment]
Will take a look.

**Comment by marcoscaceres** [comment]
@saschanaz, feel free to ping me for any guidance.

If you want see some examples: 

 * https://github.com/w3c/payment-request/pull/885 
 * https://github.com/w3c/web-share/pull/135
 * also a few examples in HTML itself - search for "transient activation" or one of the others. 

Important question will come up about if this should "consume" the user activation or not.

**Comment by saschanaz** [comment]
Already saw w3c/payment-request#885, cheat sheet 😂
