### ISSUE TITLE
Access to system clipboard on user interaction

### ISSUE THREAD

**Issue by magicalhobo** [w3c/clipboard-apis#11]
I don't see any way to access the system clipboard on mouse and keyboard events.

It would be nice if the HTML5 Clipboard API could replace workarounds like ZeroClipboard.

**Comment by hallvors** [comment]
@magicalhobo do you mean reading from clipboard (as in "pasting data") or writing to clipboard (as in "copy" or "cut") on mouse and keyboard events? The latter should work OK through the ```execCommand('copy')``` mechanism. The former currently needs a paste command triggered through trusted browser UI.

**Comment by magicalhobo** [comment]
I mainly meant copy on mouse events, like the copy button here on GitHub.

I thought that was mostly for IE, but I see other browsers have implemented it. It's a strange API, but I guess it works. Thanks.
