### ISSUE TITLE
Travis failing because python 3 now required

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/clipboard-apis#113]
Just a head up that pull requests checks are failing because BikeShed now needs python 3. Should be easy to fix in the build script. 

Just a heads up to @tabatkins - maybe good as a followup to the spec-prod email. We might be able to fix a bunch of these in one go, as I imagine everyone is probably using the same script. 

As an alternative, maybe we can look at creating a centralized GitHub Action - might be more manageable to have everything centralized and everyone using bikeshed could benefit at once.

**Comment by annevk** [comment]
FWIW, WHATWG uses https://api.csswg.org/bikeshed/ which also seems a bit better resource-wise than letting Travis pull down all of bikeshed.

**Comment by marcoscaceres** [comment]
Yeah, that's smart. I don't know how often people want to be tied to particular version.

**Comment by tabatkins** [comment]
What do you think needs to be added to the spec-prod email, Marcos? I have a comment in there already about updating Travis (it's a one-character change, generally).

**Comment by marcoscaceres** [comment]
> What do you think needs to be added to the spec-prod email, Marcos? 

Maybe just a link to a PR that shows the updated script (even if it's a one liner). Might motivate people seeing where they need to change their own scripts. I know, it's silly... maybe not needed.

**Comment by tabatkins** [comment]
On Mon, Mar 23, 2020 at 3:55 PM Marcos Cáceres <notifications@github.com> wrote:
> Maybe just a link to a PR that shows the updated script (even if it's a one liner). Might motivate people seeing where they need to change their own scripts. I know, it's silly... maybe not needed.

Not silly, but I did precisely that in the second email in the
spec-prod thread:
<https://lists.w3.org/Archives/Public/spec-prod/2020JanMar/0006.html>

**Comment by marcoscaceres** [comment]
Ok, sorry I'd missed that. Thanks @tabatkins!

**Comment by marcoscaceres** [comment]
Fixed by https://github.com/w3c/clipboard-apis/commit/6c2b4ef5d087f2c2f37c7f338d78d1a88b446642
