### ISSUE TITLE
Consider exporting "allowed to modify the clipboard" definition

### ISSUE THREAD

**Issue by saschanaz** [w3c/clipboard-apis#115]
Currently [execCommand spec uses the term](https://w3c.github.io/editing/ActiveDocuments/execCommand.html#the-copy-command) without explicit export from [this spec](https://w3c.github.io/clipboard-apis/#allowed-to-modify-the-clipboard). Since unexported terms are expected to only used within its parent spec, it should be explicitly exported to suppress the reference error from ReSpec.

**Comment by marcoscaceres** [comment]
Quick PR? 🙏
