### ISSUE TITLE
What does ClipboardItem.getType do

### ISSUE THREAD

**Issue by mkruisselbrink** [w3c/clipboard-apis#119]
There seems to be no spec text of any kind describing the getType method. Having some description of what this method does would be good, particular with regards to how it behaves when the ClipboardItem does not contain data for the given type.

**Comment by jakearchibald** [comment]
Just ran into this. In particular, I was left wondering if `getType('image/*')` did anything special.

**Comment by evilpie** [comment]
I am implementing the clipboard API in Firefox and this and other issues makes everything guess work.
`ClipboardItemDataType` is defined as `(DOMString or Blob)`, but `getType` just returns a `Blob`. How does that work? Is there a Blob created internally?

**Comment by annevk** [comment]
It seems the constructor is basically not defined? 😟

**Comment by pwnall** [comment]
/cc @garykac @dway123 for visibility.

Chrome's implementation doesn't do anything clever in `getType()`, like handling `image/*`. IOW, I think `getType()` will only return data if passed one of the elements of the array returned by `types()`.

**Comment by pwnall** [comment]
(Also, to be clear, I fully support the idea of fixing the spec. I explained what Chrome does above to unblock @evilpie.)

**Comment by evilpie** [comment]
Thanks @pwnall. I was mostly speaking in terms of what the spec wants. Because Chrome only supports creating `ClipboardItem` with a `Blob` this question doesn't really come into play.

**Comment by snianu** [comment]
Closing this issue as the PR for this has been merged: https://github.com/w3c/clipboard-apis/pull/158
