### ISSUE TITLE
Create an easier to use API

### ISSUE THREAD

**Issue by realityking** [w3c/clipboard-apis#12]
Apologies if I'm not supposed to post here, I'm not sure which is the correct venue.

While the `execCommand()` API is appropriate for an editor or similar applications, it's rather cumbersome for the common "copy something I have in memory to the clipboard" made popular by zero clipboard.

Helpful would be an API, that would allow - after an user action - setting any content to clipboard without intercepting some event. It would also make feature detection easier, `commandSupported()` seems to have several issues at least in Firefox and Chrome.

I've never written any WebIDL, so this is probably horribly wrong, but I'd see the API something like this:

```
interface Clipboard {
  void setData(DataTransferItemList data);
};

partial interface Window {
  [Replaceable] readonly attribute Clipboard clipboard;
};
```

**Comment by hallvors** [comment]
There's some work happening on this now, I think it will be fully public shortly.

**Comment by hallvors** [comment]
https://discourse.wicg.io/t/proposal-modern-asynchronous-clipboard-api/1513

**Comment by garykac** [comment]
The spec has been updated with the updated (asynchronous) API.

If you have any specific issues with the new API, please file them as separate bugs so that we can track them properly. Thanks!
