### ISSUE TITLE
"fire a clipboard event of type e" should also create the event

### ISSUE THREAD

**Issue by foolip** [w3c/clipboard-apis#13]
These should be merged:
https://w3c.github.io/clipboard-apis/#create-a-clipboard-event-object
https://w3c.github.io/clipboard-apis/#fire-a-clipboard-event

As it is, the "Dispatch an event using the ClipboardEvent interface, with its type attribute initialized to e" step of the firing algorithm doesn't make sense if the event has already been created.

Compare with:
https://html.spec.whatwg.org/#fire-a-simple-event
https://html.spec.whatwg.org/#fire-a-click-event

**Comment by hallvors** [comment]
I guess I misunderstood you yesterday. I've tried to simplify things, hope this works..

**Comment by foolip** [comment]
Thanks, and a follow-up: https://github.com/w3c/clipboard-apis/issues/16
