### ISSUE TITLE
Blob size from clipboard.read() bigger than upload original file

### ISSUE THREAD

**Issue by JackFGreen** [w3c/clipboard-apis#136]
Blob.size not match upload file.size, and blob.type is wrong

![image](https://user-images.githubusercontent.com/23187848/103865133-ac720180-50fe-11eb-87b3-e6fa4567704e.png)

**Comment by tomayac** [comment]
The clipboard re-encodes images to make sure [decompression bomb](https://bomb.codes/) attacks are useless. The file size changing on innocent images is a side effect of this.

**Comment by JackFGreen** [comment]
@tomayac Is there any way to get the original size

**Comment by tomayac** [comment]
If you have access to the original file, you can look at its [`size`](https://developer.mozilla.org/en-US/docs/Web/API/File/size).
