### ISSUE TITLE
 Arbitrary clipboard types 

### ISSUE THREAD

**Issue by annevk** [w3c/clipboard-apis#165]
As the current async clipboard API does not have a definition, extensions to it are somewhat hard to define, but here is my basic idea for arbitrary clipboard types that I think works for all parties.

The `ClipboardItem` constructor and the `ClipboardItem` `getType()` method both take a string that represents a type. As this type is a MIME type it's formatted as "`type/subtype`". The only types supported there are builtin types, such as "`text/plain`".

To extend this to allow arbitrary types, without impacting the processing of builtin types, which can be special depending on the user agent and its requirements, this proposal suggests introducing a namespace for arbitrary types. Arbitrary types will always have their data stored and read as-is, without any manipulation.

Arbitrary types are denoted by the prefix "`web `" ("`web`" followed by U+0020 SPACE) to distinguish them from builtin types. They are stored in an implementation-defined manner on the underlying OS clipboard and must not interfere with builtin types.

Expressed in JavaScript, this is how would you read an arbitrary type:

```js
const items = await navigator.clipboard.read();
const arbitraryBlob = await items[0].getType(`web ${arbitraryType}`);
```

And this is how would write one:

```js
const items = [new ClipboardItem({ `web {$arbitraryType}`: arbitraryBlob })];
navigator.clipboard.write(items);
```

@whsieh @snianu @BoCupp-Microsoft @travisleithead @johanneswilm

**Comment by BoCupp-Microsoft** [comment]
Thanks for the proposal.  Some questions below to clarify some details:

Your "web" keyword indicates that a mime-type is to be read from the platform-specific location named in the [Web Custom Format Map](https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#on-windows).  True?

The absence of the keyword means that it is read from the well-known location (assuming we're dealing with a well-known mime-type like "text/html").  True?

It is assumed that the content returned is always unsanitized whether the "web" keyword is used or not.  True?

Say on Windows, if the clipboard contained a Web Custom Format Map entry for "text/html" in "Web Custom Format 1", and the clipboard also contained the "HTML Format", you would expect at least two entries in `ClipboardItem.types`: "web text/html" and "text/html".  True?

Stating the above more generally, `ClipboardItem.types` lists all the strings that an author can supply to `ClipboardItem.getType` to access all of the content from the Web Custom Format Map and all of the well-known types present on the clipboard.  True?

**Comment by snianu** [comment]
Also cc @mbrodesser, @smaug----

**Comment by annevk** [comment]
> Your "web" keyword indicates that a mime-type is to be read from the platform-specific location named in the [Web Custom Format Map](https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#on-windows). True?

Yes.

> The absence of the keyword means that it is read from the well-known location (assuming we're dealing with a well-known mime-type like "text/html"). True?

Yes, in particular this should continue to behave as it does today.

> It is assumed that the content returned is always unsanitized whether the "web" keyword is used or not. True?

This proposal does not attempt to change the processing model for non-"web" types. (I suspect we need to allow manipulation of non-"web" as Safari does that today for privacy reasons and other browsers might want to as well. Open a new issue for this perhaps?)

> Say on Windows, if the clipboard contained a Web Custom Format Map entry for "text/html" in "Web Custom Format 1", and the clipboard also contained the "HTML Format", you would expect at least two entries in ClipboardItem.types: "web text/html" and "text/html". True?

Yes.

> Stating the above more generally, ClipboardItem.types lists all the strings that an author can supply to ClipboardItem.getType to access all of the content from the Web Custom Format Map and all of the well-known types present on the clipboard. True?

This is hard to answer as `ClipboardItem.prototype.types` (which I think is what you mean) does not have a definition today.

**Comment by BoCupp-Microsoft** [comment]
Thanks for the responses, @annevk.  Another question on a point that escaped my initial reading; you said:

> They are stored in an implementation-defined manner on the underlying OS clipboard and must not interfere with builtin types.

Amongst the [goals listed in our current proposal](https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#goals) is:

> Allow sites to represent and interact with more clipboard formats, with fine-grained control. These types will be placed on the operating system clipboard, to allow for communication between different browsers, and between web and native applications.

I believe to allow native apps the ability to communicate with web apps via multiple browser implementations, that we'll need to document, by platform, the expected shape of the web custom formats on the clipboard.  @snianu has [proposed a per-platform shape here](https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md#os-interaction-format-naming).  I'm not sure if you meant to imply the format could be different for each browser implementation or not.  Could you clarify?

**Comment by annevk** [comment]
That's a good point. The intent is to leave the API up to the OS. And indeed [implementation-defined](https://infra.spec.whatwg.org/#implementation-defined) is a poor fit for that (unless the user agent happens to be the OS). I suggest we say something like operating-system-defined.

**Comment by annevk** [comment]
It sounded good to me. Looking forward to @whsieh's take.

**Comment by snianu** [comment]
We discussed this with Google folks and agreed with this proposal -- adding a `"web"` prefix for custom format read/write. I've updated the explainer [here](https://github.com/w3c/editing/blob/gh-pages/docs/clipboard-pickling/explainer.md). Please take a look and let us know if you have any concerns/questions. @annevk @mkruisselbrink @pwnall @whsieh @mbrodesser

**Comment by annevk** [comment]
I would suggest we drop "pickling" from the name and use something like "Custom Clipboard Types" or "Web Clipboard Types". It's also not clear to me that OS-Interaction works for macOS given the discussion around that to date, but otherwise it seems fine. We should probably include the 100 limit in the eventual specification to prevent egregious platform differences.

**Comment by tomayac** [comment]
I suggest we add some sort of feature-detection for custom and classic formats. This is actual nightmare-ish application code of mine that only makes sure copying works on three browsers (Firefox, Chrome, Safari): https://github.com/tomayac/SVGcode/blob/b29b27dadf2cf3c8aefb77e2c3db9feb0872d91d/src/js/clipboard.js#L64-L136

My suggestion would be to add a static function on `ClipboardItem`

```js
ClipboardItem.supports('image/webp');
// `false`
ClipboardItem.supports('image/png');
// `true`
ClipboardItem.supports('web');
// `true`
```

Or maybe even better (and similar to `await BarcodeDetector.getSupportedFormats()`):

```js
await ClipboardItem.getSupportedFormats()
// `['text/plain', 'image/png', 'web']`

Not sure how to express custom types here, as a ground for discussion I just went with `"web"`. What do you think?
```

**Comment by annevk** [comment]
I'm not sure I like enumeration per se (you are likely to run into ordering issues), but `supports(type)` seems reasonable.

**Comment by tomayac** [comment]
> I'm not sure I like enumeration per se (you are likely to run into ordering issues), but `supports(type)` seems reasonable.

SGTM, opened as a separate Issue https://github.com/w3c/clipboard-apis/issues/170.

**Comment by snianu** [comment]
> I would suggest we drop "pickling" from the name and use something like "Custom Clipboard Types" or "Web Clipboard Types".

Sounds good. I'll remove all references to pickling from the explainer.

> We should probably include the 100 limit in the eventual specification to prevent egregious platform differences.

Yes, I'm planning to add that to the specification.

**Comment by tomayac** [comment]
> Just curious, why can't the author enumerate the `types` after the read operation to see if a particular format is available or not? That way you don't have to add special code for this feature. Here is a sample code (mentioned in the explainer):
> 
> ```
> const item = items[0]
> if (item.types.includes("web text/custom")) {
>   // prefer this web app's custom markup if available
>   const custom_markup = await (await clipboardItem.getType("web text/custom")).text()
>   // process the custom markup...
> } 
> else if (types.includes("web text/html")) {
>   // native apps may write "web text/html" in addition to "text/html", prefer it
>   const html = await (await clipboardItem.getType("web text/html")).text();
>   // process the html...
> } 
> else if (types.includes("text/html")) {
>   // process html if available
>   const html = await (await clipboardItem.getType("text/html")).text();
>   // process the html...
> }
> ```

Just to be sure, this is about _writing_ to the clipboard. See my [sample code](https://github.com/tomayac/SVGcode/blob/b29b27dadf2cf3c8aefb77e2c3db9feb0872d91d/src/js/clipboard.js#L64-L136) and the comments.

**Comment by whsieh** [comment]
The overall plan sounds reasonable to me. Thank you for writing this up! One thing I'd like to clarify — would this proposal allow for WebKit's clipboard sanitization policy to apply when reading and writing "web text/html" across different origins?

More concretely — if site foo.com writes "web text/html" to the clipboard, we would want to only expose sanitized data on "text/html" to bar.com. However, if a native app writes "web text/html" into the system clipboard, we would allow bar.com to read it as "web text/html" with no sanitization.

**Comment by annevk** [comment]
The idea is that if you only write "web text/html" you cannot read "text/html" (as there's no such entry). If you write both "web text/html" and "text/html", then a "text/html" read can be sanitized of course.

**Comment by whsieh** [comment]
I see — is it the case that site authors should always write both "web text/html" as well as "text/html", then, when copying markup?

(That is, for compatibility with other websites that have not yet adopted "web text/html", in addition to browsers, such as WebKit, that would intentionally hide "web text/html" when copying and pasting across security origins).

**Comment by annevk** [comment]
WebKit would not support arbitrary types across origins? What is the concern there given it's opt-in from all sides?

**Comment by sspi** [comment]
Perhaps a more aggressive term than "web" as "uncontrolled", "unsanitized", "unchecked" or "dangerous" (...) better alert the developers and reassure the Webkit team?

**Comment by whsieh** [comment]
> WebKit would not support arbitrary types across origins? What is the concern there given it's opt-in from all sides?

So in shipping Safari, our DataTransfer APIs don't allow for cross-origin transfer of custom data types, since this could be abused as a potential tracking mechanism. With the async clipboard API, we currently uphold these same rules for the same reasons (as well as consistency with the legacy API).

**Comment by hober** [comment]
> WebKit would not support arbitrary types across origins? What is the concern there given it's opt-in from all sides?

I believe the concern is that `evil1.example` and `evil2.example` could collude.

**Comment by snianu** [comment]
> I believe the concern is that evil1.example and evil2.example could collude.

Isn't this true for native apps on Mac platforms as well? An evil1 native app could collude with evil2.example?
Wondering since @whsieh said 
> However, if a native app writes "web text/html" into the system clipboard, we would allow bar.com to read it as "web text/html" with no sanitization.

**Comment by annevk** [comment]
As @whsieh alluded to in a meeting there's a higher level of trust in native apps (they also get to pretend they are same-origin).

If there is active collusion it might be hard to prevent even with builtin types, but I guess it would show up if the user pasted in a non-colluding environment. (E.g., if colluding parties prefix copied text and remove that prefix when pasting.)

**Comment by DrRataplan** [comment]
I am very existed about this proposal! We are building an XML editor in which we would love to have a way to initiate a `paste` from a user interaction. Because we are working with XML, we have the need to input a non-standard mimetype to the clipboard: `application/xml`. We have everything working in Chrome 104: write and read to the `web application/xml` mimetype.

Our context: we write `text/plain`, `text/html`, `application/xml` and `application/json` to the clipboard. The first two for interoperability with other applications, the last two for our editor specifically. 

Ideally, we want to use the async clipboard IFF there is custom mimetype support and instruct using the shortkeys in all other cases.

We are however stuck at how we should _detect the support of arbitrary mimetypes for the clipboard_. Specifically the case where the async clipboard API is available but custom mimetypes are not. IE, Chrome version 103 and earlier. If Firefox would take the same process as Chrome (allow the normal mimetypes before the arbitrary ones), we are unable to detect this.

With the current APIs we have a difficult time detecting whether something is pasted from an external source (`text/plain` and `text/html` are present) versus pasting from our editor, but w/o arbirtary mimetype support (only `text/plain` and `text/html` would be available).

Am I overlooking something or is this case indeed very tricky to detect?

**Comment by tomayac** [comment]
I have opened https://github.com/w3c/clipboard-apis/issues/170 in which I propose the following:

```js
ClipboardItem.supports('image/webp');
// `false`
ClipboardItem.supports('image/png');
// `true`
ClipboardItem.supports('web');
// `true`
```

**Comment by snianu** [comment]
> > WebKit would not support arbitrary types across origins? What is the concern there given it's opt-in from all sides?
> 
> So in shipping Safari, our DataTransfer APIs don't allow for cross-origin transfer of custom data types, since this could be abused as a potential tracking mechanism. With the async clipboard API, we currently uphold these same rules for the same reasons (as well as consistency with the legacy API).

@whsieh For cross-origin copy/paste using DataTransfer APIs, Safari only allows to read sanitized HTML from the standard html format -- Apart from what Ryosuke described in [this ](https://github.com/w3c/clipboard-apis/issues/150#issuecomment-973293309)comment, are there any other reasons as to why this approach was chosen by Safari?

**Comment by snianu** [comment]
@annevk

> @whsieh For cross-origin copy/paste using DataTransfer APIs, Safari only allows to read sanitized HTML from the standard html format -- Apart from what Ryosuke described in [this ](https://github.com/w3c/clipboard-apis/issues/150#issuecomment-973293309)comment, are there any other reasons as to why this approach was chosen by Safari?

**Comment by DavidMulder0** [comment]
Is it exepcted according to the spec that these `web `-types do not get exposed through the 'old' transfer information on the Paste event (`event.clipboardData.types` never includes `web `-types in Chrome)?

**Comment by snianu** [comment]
@DavidMulder0 Yes, these web custom types are only for async clipboard APIs. However, there are browser specific clipboard formats (e.g in Chromium we have "Chromium Web Custom MIME Data Format") that allow you to read/write custom types from within the browser via DataTransfer APIs, but it's not interoperable with native apps and async clipboard APIs.
