### ISSUE TITLE
`ClipboardItem` constructor should throw when `items` are empty

### ISSUE THREAD

**Issue by mbrodesser** [w3c/clipboard-apis#169]
```
const c = new ClipboardItem([]);
```

Chrome and Firefox both throw a `TypeError`. The spec doesn't cover this case.

CC @snianu 
Keeping this separate from #158 to not widen its scope.

**Comment by mbrodesser** [comment]
@snianu let's pull #158 first. This is a minor issue.

**Comment by EdgarChen** [comment]
Now spec throws TypeError when items is empty after #158, i.e.

> The new ClipboardItem(items, options) constructor steps are:
    If items is empty, then throw a [TypeError](https://webidl.spec.whatwg.org/#exceptiondef-typeerror).

Could we close this?

**Comment by snianu** [comment]
I think we can close this. Thanks for the reminder!
