### ISSUE TITLE
Feature detection for supported clipboard formats

### ISSUE THREAD

**Issue by tomayac** [w3c/clipboard-apis#170]
Migrated and adapted from https://github.com/w3c/clipboard-apis/issues/165#issuecomment-1041668421:

I suggest we add some sort of feature-detection for custom and classic formats. This is actual nightmare-ish application code of mine that only makes sure copying works on three browsers (Firefox, Chrome, Safari): https://github.com/tomayac/SVGcode/blob/b29b27dadf2cf3c8aefb77e2c3db9feb0872d91d/src/js/clipboard.js#L64-L136

My suggestion would be to add a static function on `ClipboardItem`

```js
ClipboardItem.supports('image/webp');
// `false`
ClipboardItem.supports('image/png');
// `true`
ClipboardItem.supports('web');
// `true`
```

Not sure how to express custom types here, as a ground for discussion I just went with `"web"`. What do you think?

**Comment by annevk** [comment]
@snianu's [comment](https://github.com/w3c/clipboard-apis/issues/165#issuecomment-1041846374) needs addressing. (Also, once the processing model for the existing features is defined it might also reveal some ways that feature testing can work.)

**Comment by tomayac** [comment]
> @snianu's [comment](https://github.com/w3c/clipboard-apis/issues/165#issuecomment-1041846374) needs addressing. (Also, once the processing model for the existing features is defined it might also reveal some ways that feature testing can work.)

Responded over in #165. I think there was a misunderstanding. Feature detection would mostly be needed to know what can be written.

**Comment by snianu** [comment]
> Feature detection would mostly be needed to know what can be written.

Ah, that is indeed a problem for web authors. It would probably be beneficial to the web authors to also expose what mandatory types are supported by a browser? e.g. Chrome supports reading/writing SVG(`image/svg+xml`) using async APIs and Safari supports `text/uri-list`. Adding the agenda tag so we can discuss this in the EditingWG meeting. Thanks for reporting this issue!

**Comment by annevk** [comment]
So while you can feature detect by attempting to write a builtin type, that's not great as writing is an asynchronous operation. Therefore it would be better to have that information available synchronously upfront. (You also might want to write multiple types at the same time.)

**Comment by snianu** [comment]
@BoCupp-Microsoft

**Comment by snianu** [comment]
Looks like this is a highly requested feature. Saw at least couple old issues(https://github.com/w3c/clipboard-apis/issues/67) in this repo requesting to expose this data to web authors.

**Comment by BoCupp-Microsoft** [comment]
In today's Editing WG meeting we resolved that ClipboardItem.supports should be added to the clipboard spec.  I'll remove the Agenda+ label and expect this issue to be closed with a future PR.

**Comment by martinthomson** [comment]
A few comments on this change:

1. The fingerprinting risk was not identified in the privacy section.
2. "If type is in [mandatory data types](https://w3c.github.io/clipboard-apis/#mandatory-data-types) or [optional data types](https://w3c.github.io/clipboard-apis/#optional-data-types), then return true."  This reads as if you just concatenate the lists from each section, but I think that the second set needs to be filtered, with optional types that are not supported by the UA being removed.

**Comment by yisibl** [comment]
Should we case sensitive the `web` prefix? Are there any other APIs I can refer to?

The current implementation in Chrome returns the following:

```js
ClipboardItem.supports('weB text/html') // → false
ClipboardItem.supports('web text/html') // → true
ClipboardItem.supports('web text/Html') // → true
```

**Comment by snianu** [comment]
@yisibl Please see https://github.com/w3c/clipboard-apis/pull/192#issuecomment-1726703751 for context on this change.

**Comment by yisibl** [comment]
@EdgarChen Which version of Firefox supports `ClipboardItem.supports()`? 

[Browser compatibility in MDN](https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem#browser_compatibility) needs to be updated.

**Comment by saschanaz** [comment]
It's landed very recently and MDN update will be tracked by the `dev-doc-needed` keyword there. https://bugzilla.mozilla.org/show_bug.cgi?id=1858788
