### ISSUE TITLE
The MIME type checking should ignore the "web " prefix

### ISSUE THREAD

**Issue by ziyunfei** [w3c/clipboard-apis#178]
<img width="738" alt="image" src="https://user-images.githubusercontent.com/1276859/172635747-0b483f22-6074-40e6-81d1-70f0f220b69a.png">

@snianu

**Comment by snianu** [comment]
Nice bug! Agreed that it should ignore the "web " prefix in this case. I'll fix this in Chromium, but adding @annevk & @edgarchen as FYI.

**Comment by annevk** [comment]
Should also make sure this is specified properly and has test coverage.
