### ISSUE TITLE
Add intro to 4. APIs from other specifications

### ISSUE THREAD

**Issue by MichielBijl** [w3c/clipboard-apis#19]
It would be nice to have some sort of introduction as to what the significance of these lists of API's is.

**Comment by hallvors** [comment]
I agree - could it be this simple?

> Algorithms in this document rely on several APIs defined in other web platform specifications and recommendations. Below is a list of all methods, properties and definitions this document relies on.

**Comment by MichielBijl** [comment]
Looks good to me :+1:
