### ISSUE TITLE
Definition of editing host

### ISSUE THREAD

**Issue by MichielBijl** [w3c/clipboard-apis#20]
Under 5. Terminology there is a link to a link to an API (under 4. APIs from other specs) to [editing host](https://w3c.github.io/editing/#editing-host). The partial of that link however, doesn't exist, leading readers to keep and wonder what an editing host is ;)

**Comment by hallvors** [comment]
https://w3c.github.io/editing/contentEditable.html#dfn-editing-host

**Comment by garykac** [comment]
Broken link fixed as part of the bikeshed conversion: https://github.com/w3c/clipboard-apis/commit/5c704c9d92252232a7f90fb7ed4dc1eb33b0d7f8
