### ISSUE TITLE
`supports` should take a dictionary instead of a DOMString as argument for readability

### ISSUE THREAD

**Issue by snianu** [w3c/clipboard-apis#211]
From [TAG review feedback](https://github.com/w3ctag/design-reviews/issues/901#issuecomment-1905805024), 
"`supports()` is a rather generic name, but the type of support being tested is very specific. This could hinder both learnability and future extensibility. One way to address that would be to adopt a dictionary argument (e.g. `ClipboardItem.supports({type: "image/webp"})`). If it later becomes clear that MIME type is the primary criteria that support queries are used for, a string argument could be supported as an overloaded shortcut."

**Comment by annevk** [comment]
The way we did this matches precedent in HTML and still makes sense to me. I'd argue that once we need a lot of things we can then add the overload.

**Comment by snianu** [comment]
Since the TAG closed the original issue with a satisfied resolution for the existing `supports` method, closing this issue as well.
