### ISSUE TITLE
Be explicit about before* events

### ISSUE THREAD

**Issue by MichielBijl** [w3c/clipboard-apis#24]
> The before* events can be used to override the internal logic.

It would increase clarity if all event names were to be written in full here.

> The beforecopy, beforecut, and beforepaste events can be used to override the internal logic.

**Comment by MichielBijl** [comment]
Alternatively—as the term before* events is used more often—would it be better to call them something different? For example group them under “clipboard events”.

Example usage:

> The clipboard events can be used to override the internal logic.

> 6.2 Processing model for clipboard events

> Typically, the clipboard events fire before a menu is shown to the user

I'm not sure how this would play with the actions (maybe those can be grouped as clipboard actions?).

**Comment by hallvors** [comment]
There has been some pushback against the before* events, they are not well implemented anywhere (not even in IE) so I'm leaning towards just killing them. Obviously that would solve this wording problem too :)

**Comment by garykac** [comment]
If you do decide to keep the before{copy/cut/paste} events, note that referring to them as before* seems like it should include beforeinput as well.

So, +1 to rewording this (if you keep them).

**Comment by hallvors** [comment]
Killed these events - see #25
