### ISSUE TITLE
Clarify the algorithm for setting target of a clipboard event in 7.2 Processing model for event dispatch

### ISSUE THREAD

**Issue by nickolay** [w3c/clipboard-apis#29]
https://www.w3.org/TR/clipboard-apis/#processing-model-for-event-dispatch has this text:

> Set target as follows:
> - If the context is editable:
>   - Let target be the element that contains the start of the selection in document order, or the body element if there is no selection or cursor.
> - Else, if the context is not editable
>   -  Let target be the focused node, or the body element if no node has focus. 

It ought to define what **the** context is (there's a [definition](https://www.w3.org/TR/clipboard-apis/#dfn-editable-context) of what it means for **a** context to be editable) - presumably the focused node?

"the start of the selection" and "the focused node" ought to link to the corresponding specs. Would it make sense to define it in terms of existing APIs perhaps?

Also [the definition of "the body element"](https://www.w3.org/TR/clipboard-apis/#dfn-the-body-element) in clipboard-apis links to [the definition of &lt;body>](https://www.w3.org/TR/html/sections.html#the-body-element) in the HTML spec, while it's probably meant to point specifically to [the definition of the term "The body element of a document"](https://www.w3.org/TR/html/dom.html#the-body-element-0) in the HTML spec.

**Comment by garykac** [comment]
The definition of the term "body" is at: https://www.w3.org/TR/html/dom.html#dom-document-body

**Comment by annevk** [comment]
No, "the body element" is at https://html.spec.whatwg.org/multipage/dom.html#the-body-element-2.

**Comment by garykac** [comment]
"the body element" link fixed in https://github.com/w3c/clipboard-apis/commit/e46427086e943da7ad7e99958b80ed164d9c9849

**Comment by garykac** [comment]
Links to "focusable area" dfn added in https://github.com/w3c/clipboard-apis/commit/f4b6719ca860d546af75a8b432fe7e71d1981a71

**Comment by garykac** [comment]
As far as I can tell, there is no linkable definition for "the start of the selection".  The HTML spec just uses the text "start of the selection".
