### ISSUE TITLE
Where would one get a DataTransfer to hand to the ClipboardEvent constructor?

### ISSUE THREAD

**Issue by bzbarsky** [w3c/clipboard-apis#33]
DataTransfer objects can't be created by script as things stand; they can only be gotten out of an existing ClipboardEvent or DragEvent.  That makes the constructor version with a DataTransfer dictionary member somewhat useless in practice...  Maybe the answer is that we should in fact have a way of constructing DataTransfer objects?

Note that Firefox currently ships a version of ClipboardEventInit that takes data and dataType strings and internally constructs a DataTransfer from them....

**Comment by bzbarsky** [comment]
Looks like what Firefox ships is what was defined in https://www.w3.org/TR/2015/WD-clipboard-apis-20150421/ and then it got changed to the current thing by the time https://www.w3.org/TR/2015/WD-clipboard-apis-20151215/ got published.

**Comment by RByers** [comment]
Thanks for raising this Boris.  A common use case for Event constructors is to clone / wrap an event with a few changes (eg. I see event delegation libraries do this sometimes).  That use case would still be possible, right?

In general I think DOM folks (@annevk, @smaug---- IIRC) have said we want event constructors to follow a pretty rigid pattern of just taking the Event attributes directly and not having any smarts / conversions.  If we agree to that pattern then I suggest we [proceed with shipping](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/5zb6MESKRog) the constructor as speced now in blink, and explore adding ways to create DataTransfer objects (possibly low priority though).  WDYT?

**Comment by bzbarsky** [comment]
> That use case would still be possible, right?

That's correct.

The rest of the questions are probably better directed at @smaug----

**Comment by RByers** [comment]
> The rest of the questions are probably better directed at @smaug----

Thanks.  Let me know if you think this issue should delay blink shipping the ClipboardEvent constructor though.  There's no real urgency there except that we're doing a systematic pass at fixing lots of minor spec conformance issues to enable some tooling that auto-flags spec conformance issues.

**Comment by bzbarsky** [comment]
I should also add that the example in the spec at https://w3c.github.io/clipboard-apis/#clipboard-event-interfaces says:

    var pasteEvent = new ClipboardEvent('paste');
    pasteEvent.clipboardData.items.add('My string', 'text/plain');

which would throw if the spec were actually implemented as currently written...

**Comment by bzbarsky** [comment]
The real question is whether there are sites depending on the Firefox behavior.  I'd expect not, so shipping this in Blink is probably fine.  We should just define some constructor bits for DataTransfer to make this all sane.  @annevk @domenic

**Comment by foolip** [comment]
The weirdness with `DataTransfer` was previously discussed in https://github.com/w3c/clipboard-apis/issues/10 and it ended up looking like `DragEvent`, which also has a pretty useless constructor.

A `DataTransfer` constructor would be useful for tests of `ClipboardEvent` and `DragEvent`, I agree.

+@LoonyBean

**Comment by smaug----** [comment]
I agree that DataTransfer having a ctor could be useful for testing. And even without that passing dataTransfer from trusted drag event to clipboard event might simplify some scripts.

**Comment by domenic** [comment]
@smaug---- can you help explain how such a constructor would work, over in https://github.com/whatwg/html/issues/2190 ?

**Comment by smaug----** [comment]
Not sure what to explain there. While handling some dnd event, one may want to dispatch untrusted clipboard event (and initialize the dataTransfer using the object from dnd).

**Comment by domenic** [comment]
@smaug---- how do you initialize the DataTransfer object "using the object from the dnd"? If we are talking about the same "object", then that object is a spec abstract data structure (the "drag data store"), and there's no way to copy it over.

**Comment by smaug----** [comment]
There is no copying. DragEvents have 
readonly attribute DataTransfer? dataTransfer;
and ClipboardEvents have 
readonly attribute DataTransfer? clipboardData;

One can reuse the same DataTransfer object in ClipboardEvents.

something like
`
element.ondrop = function(e) {
  element.dispatchEvent(new ClipboardEvent("paste", {clipboardData: e.dataTransfer}));
}

element.onpaste = function(e) {
  // handle paste and drop...
}
`

Or are we talking about different things here?

**Comment by domenic** [comment]
Yes, we appear to be talking about different things. I am responding to your claim that

> I agree that DataTransfer having a ctor could be useful

by asking how such a constructor could work. But your example does not include any usage of the DataTransfer constructor, so now I am confused why you think a constructor would be useful.

**Comment by garykac** [comment]
We have a need for a DataTransfer constructor for the async Clipboard API.

For this use case, the DataTransfer would be created with an empty drag-data-store and with Read/Write access.  Items would be added into the store after the DataTransfer was created.

[1] Clipboard API proposal: https://github.com/garykac/clipboard/blob/master/clipboard.md
[2] Async Clipboard API: https://w3c.github.io/clipboard-apis/#clipboard-interface

**Comment by garykac** [comment]
A constructor was added to DataTransfer in https://github.com/whatwg/html/commit/688a102b52c7050a6808a05c5d8fe149c0937fd7

**Comment by foolip** [comment]
Looks like there aren't any tests for `new ClipboardEvent` that use the new constructor, I filed https://github.com/w3c/web-platform-tests/issues/7857.

**Comment by guest271314** [comment]
@domenic fwiw followed the links and share the below as not certain with whom else to share the results, if not applicable here will delete when advised the same.

```
    class _DataTransfer {
      constructor() {
        return new ClipboardEvent("").clipboardData || new DataTransfer();
      }
    }
```

initially appeared to be a promising solution for Chromium 62 and Firefox 57 following previous attempts for same code solution at both browsers https://gist.github.com/guest271314/7eac2c21911f5e40f48933ac78e518bd, though `.files` property of created `DataTransfer` object is not retained after setting `.files` property of `<input type="file">` element to that `FileList` object http://plnkr.co/edit/1TSHMOWoyGEWRYKIEf7S?p=preview see version 1, to reproduce click `<label>` element twice. 

Is the expected result for `DataTransfer` instance `.files` property to not persist? Or are values set using   expected to be deleted from the object at some point? Does the specification state that `.files` property of a created `DataTransfer` object, and, or `File` objects set using `DataTransferItems` `.add()` metod should be deleted at an arbitrary point in the future, for example, when the `.files` property is set an `<input type="file">` element?

It was necessary to create a new instance of `DataTransfer` at each `click` of `<label>` to achieve same result at Chromium 62 and Firefox 57, see version 2. Is this the expected behaviour according to the specification?
