### ISSUE TITLE
Remove file “ECHIDNA”

### ISSUE THREAD

**Issue by tripu** [w3c/clipboard-apis#35]
It's identical to `W3CTRMANIFEST`, which is the one being used by the automatic publication system.

**Comment by garykac** [comment]
Is there a reason not to submit/merge this change?

**Comment by tripu** [comment]
I think it can be removed. I just wanted to confirm with the team contacts, @ylafon and @siusin.

**Comment by plehegar** [comment]
Done
https://github.com/w3c/clipboard-apis/commit/77a902b75eefa013b0a8e77659f612fe7163cd2b
