### ISSUE TITLE
Import and set up ReSpec

### ISSUE THREAD

**Issue by tripu** [w3c/clipboard-apis#36]
Automatic publication is failing; cf [`lists.w3.org/Archives/Public/public-tr-notifications/2016Dec/0085.html`](https://lists.w3.org/Archives/Public/public-tr-notifications/2016Dec/0085.html)

[`labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fw3c.github.io%2Fclipboard-apis%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dclipboard-apis`](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Fw3c.github.io%2Fclipboard-apis%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dclipboard-apis) returns an error, and &ldquo;Not a ReSpec source document?&rdquo;

See the [user's guide](https://github.com/w3c/respec/wiki/User's-Guide)

**Comment by annevk** [comment]
Well, the document was converted to Bikeshed. I don't think we want to undo that.

**Comment by tripu** [comment]
Oh, is that so?

In that case, config files used by the automatic publication system must be updated, too (`.travis.yml`, `W3CTRMANIFEST`, `ECHIDNA`).

**Comment by garykac** [comment]
Can this be closed now? Or are there further issues with Automatic Publishing that need to be addressed?

**Comment by tripu** [comment]
> *&ldquo;Are there further issues with Automatic Publishing that need to be addressed?&rdquo;*

Spec generation with Bikeshed is not configured well. Last published version was [on 13 Dec 2016](https://www.w3.org/TR/2016/WD-clipboard-apis-20161213/); all attempts since then [have failed](https://www.w3.org/Search/Mail/Public/search?keywords=&hdr-1-name=subject&hdr-1-query=clipboard-apis&index-grp=Public_FULL&index-type=t&type-index=public-tr-notifications).

**Comment by siusin** [comment]
There seems no need to convert this document back to ReSpec...

Bikeshed has an [interface](https://tabatkins.github.io/bikeshed/#echidna-hooks) to enable the autopublication. Try <code>bikeshed echidna --u USERNAME --p PASSWORD --d DECISION_URL</code>. Let us know in case of any problem.

**Comment by plehegar** [comment]
I removed the respect configuration.

https://github.com/w3c/clipboard-apis/commit/7805ffb3be6a7fb3ade4261be2390b1490c11290

@garykaz, your document is not under automatic publishing, but you can manually trigger the publication as @siusin suggested.
