### ISSUE TITLE
Aling 'set clipboard event target' spec. to current implementation 'out there'

### ISSUE THREAD

**Issue by popek777** [w3c/clipboard-apis#40]
[This example](https://jsfiddle.net/hx4m0bLc/6/) shows that current implementation of setting clipboard event target in e.g. chromium based browsers and firefox does not follow the [spec.](https://w3c.github.io/clipboard-apis/#to-fire-a-clipboard-event) (point 6) (handler installed on not-editable element is invoked, which is against the spec.)

[Other example](https://jsfiddle.net/mwrobel/hx4m0bLc/16/) which follows [spec.](https://w3c.github.io/clipboard-apis/#to-fire-a-clipboard-event) works on firefox but doesn't work on chromium based browsers.

Since there is a code 'out there' which depends on implementation rather then spec., I would suggest to change the [spec.](https://w3c.github.io/clipboard-apis/#to-fire-a-clipboard-event) point 6 to follow current implementations:

(...)

Let target be set as follows:

If selection is [empty](https://www.w3.org/TR/selection-api/#dfn-empty):
 - Set target to be the DOM anchor of the focusable area, or the body element if no node has focus.
else
 - Set target to be the element that contains the start of the selection in document order, or the body element if there is no selection or cursor.

(...)

or even simpler:

(...)
Set target to be the element that contains the start of the selection in document order, or the body element if there is no selection or cursor.
(...)

**Comment by gked** [comment]
@popek777 your reasoning makes sense. I personally like your second proposal. If there are no objections, I'll create a PR for this change.

**Comment by popek777** [comment]
@gked no objections from me. I prefer second as well (it's simpler and already implemented in chromium)
