### ISSUE TITLE
Spec does not auto-deploy when changes are made

### ISSUE THREAD

**Issue by garykac** [w3c/clipboard-apis#68]
The last time the Clipboard spec was deployed was on 25 Jan, and recent changes have not been picked up.

Do you know if something is broken with our setup?

(And are there docs for how this should work? I'm wondering if this is something I can invesgate/fix myself -- Thanks!)

**Comment by siusin** [comment]
@garykac There was a problem with Travis-CI earlier, lots of W3C repository builds seemed to have been turned off. I've turned the clipboard repo back on. We are not sure about why this happened again, please let us know if there's still problem with the build.

**Comment by garykac** [comment]
Seems to work now. Thanks!
